collections:
  chapters:
    output: true
  other_parts:
    output: true

defaults:
  - scope:
      path: ""
      type: "other_parts"
    values:
      layout: "other_part"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
  - scope:
      path: ""
    values:
      layout: "default"
